### ISSUE TITLE
 Need the code urgently, thanks!  

### ISSUE THREAD

**Issue by dddeanwang** [arlenejohn/CNN_sleep_apnea#1]
Hello, I am currently doing some experiments about apnea detection with the UCDDB data set, but the result is awful. I think it may be related to the preprocessing step. So I searched many articles until I found that the accuracy result  in your newest article can reach 100%. That's amazing! Then I found your github homepage and wanted to see how you deal with the data, but I haven't waited until the update, so I'm urgently  need the relevant code , thanks very much!!!

**Comment by arlenejohn** [comment]
Hi Dean! I will share the code for the CNN model by today or tomorrow. Hope that works!

**Comment by dddeanwang** [comment]
Thank you soooooo much!

**Comment by arlenejohn** [comment]
Just shared the code and data and models and files.
